# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autoproof < Formula
  desc "Command-line interface for automatic code & content protection"
  homepage "https://github.com/Autoproof/homebrew-autoproof"
  version "0.1.13"

  on_macos do
    on_intel do
      url "https://github.com/Autoproof/cli/releases/download/v0.1.13/autoproofcli_Darwin_x86_64.tar.gz"
      sha256 "947cda6a0b44294d6225ad898eaee68b4bdf9a0bea28c4706b568abc5bc639cd"

      def install
        bin.install "autoproofcli"
      end
    end
    on_arm do
      url "https://github.com/Autoproof/cli/releases/download/v0.1.13/autoproofcli_Darwin_arm64.tar.gz"
      sha256 "25d9b1e2aff248190109405893112a31b823a34fa0019a3565c93646b00382e9"

      def install
        bin.install "autoproofcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Autoproof/cli/releases/download/v0.1.13/autoproofcli_Linux_x86_64.tar.gz"
        sha256 "4d7d72848bac03e862f064ce88d4caefe356f9f0808a10b745f5a24ac2da8381"

        def install
          bin.install "autoproofcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Autoproof/cli/releases/download/v0.1.13/autoproofcli_Linux_arm64.tar.gz"
        sha256 "a63f849dce02020248f117d235c146beff186ccf59757008b664da93cf92b9a9"

        def install
          bin.install "autoproofcli"
        end
      end
    end
  end
end
