# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autoproof < Formula
  desc "command-line interface for automatic code & content protection"
  homepage "https://github.com/Autoproof/homebrew-autoproof"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Autoproof/cli/releases/download/v0.1.5/autoproofcli_Darwin_arm64.tar.gz"
      sha256 "ebbab8317401e9ed85ed6111eda00444039bdf26ecdabff24b9fa6cc7c795410"

      def install
        bin.install "autoproofcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Autoproof/cli/releases/download/v0.1.5/autoproofcli_Darwin_x86_64.tar.gz"
      sha256 "2dd10a4d4770a06e7e9df3d14c6d4293b444f5774b7d0a8fa780befb6c9d51ae"

      def install
        bin.install "autoproofcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Autoproof/cli/releases/download/v0.1.5/autoproofcli_Linux_arm64.tar.gz"
      sha256 "d012e526dc61d8e48d6b8cfb5352e15714e3570033d237b66990aa3857bfe245"

      def install
        bin.install "autoproofcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Autoproof/cli/releases/download/v0.1.5/autoproofcli_Linux_x86_64.tar.gz"
      sha256 "a6dfc874fedbe56b6720bd242c96dddc21b6a72bf0f2cc5e8235bd4c938935b3"

      def install
        bin.install "autoproofcli"
      end
    end
  end
end
